# Exercícios


1. Importe NumPy como `np`

In [ ]:
F

2. Crie um array com 10 zeros

In [ ]:
F

3. Crie um array com 10 'uns'

In [ ]:
F

4. Crie um array com 10 'cincos'

In [ ]:
F

5. Crie um vetor de números inteiros de 10 ate 50

In [ ]:
F

6. Crie um vetor com o numeros pares de 10 até 50

In [ ]:
F

7. Crie uma matriz $3 \times 3$ com os valores de 0 até 8

In [ ]:
F

8. Crie uma matriz identidade $7 \times 7$

In [ ]:
F

9. Use numpy para gerar um número aleatório entre 0 e 1

In [ ]:
F

10. Use o numpy para gerar 25 números aleatório de distribuição normal padrão (gaussiana com média $\mu = 0$ e desvio padrão $\sigma = 1$)

In [ ]:
F

11. Crie a matrix abaixo

```python
array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])
```

In [ ]:
F

12. Crie um array de 20 elementos igulmente espaçados entre 0 e 1:

In [ ]:
F

13. Dada a matrix abaixo,

```python
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

obtenha as seguintes matrizes por indexação e se necessário, reshape:
*
```python
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```
*
```python
array([[ 2],
       [ 7],
       [12]])
```
*
```python
array([21, 22, 23, 24, 25])
```
*
```python
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

14. Some todos os valores da matriz

In [ ]:
F

15. Some todas as colunas da matriz

16. Calcule o desvio padrão por coluna